FROM node:latest AS builder

ARG TAG=develop

WORKDIR /app
COPY . .

RUN make setup
RUN make build-ui-kit


FROM nginx:alpine

EXPOSE 80

COPY --from=builder --chown=nginx:nginx /app/ui-kit/styleguide /app
COPY --chown=nginx:nginx .nginx/ui-kit.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
