FROM node:latest AS builder

ARG TAG=develop

WORKDIR /app
COPY . .

RUN make setup
RUN make build-web


FROM nginx

EXPOSE 80

COPY --from=builder --chown=nginx:nginx /app/web/dist /app

COPY --chown=nginx:nginx .nginx/entrypoint.sh /app/entrypoint.sh
COPY --chown=nginx:nginx .nginx/web.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT [ "/app/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
