export default {
  authorizationCode: 'authorizationCode',
  checkout: 'checkout',
  confirmationCode: 'confirmationCode',
  downpayment: 'downpayment',
  finalInstallments: 'finalInstallments',
  finalPayLater: 'finalPayLater',
  initial: 'initial',
  installmentPlan: 'installmentPlan',
  internalServerError: 'internalServerError',
  rejected: 'rejected',
  scanConfirm: 'scanConfirm',
  scanError: 'scanError',
  upload: 'upload',
  welcomeBack: 'welcomeBack',
};
